# Tails
typeset -g POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=''
typeset -g POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL=''

# Left prompt
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon context dir)

# Right prompt
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(command_execution_time time)

# os_icon
typeset -g POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION='󰣇 '
typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=16
typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=255

# context
typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND=16
typeset -g POWERLEVEL9K_CONTEXT_BACKGROUND=251

# dir
typeset -g POWERLEVEL9K_DIR_FOREGROUND=16
typeset -g POWERLEVEL9K_DIR_BACKGROUND=247

# command_execution_time
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=16
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=251

# time
typeset -g POWERLEVEL9K_TIME_FOREGROUND=16
typeset -g POWERLEVEL9K_TIME_BACKGROUND=255

# Configurations
typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
